"""YouTube channel manager — handles YouTube Data API uploads and metadata."""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from core.config import get_settings
from core.message_bus import get_bus

logger = logging.getLogger(__name__)


class YouTubeChannelManager:
    """Manages YouTube Data API v3 interactions."""

    def __init__(self):
        self.settings = get_settings()
        self.bus = get_bus()

    async def upload_video(self, script_data: dict[str, Any], video_path: str | None = None) -> dict:
        """
        Upload a video to YouTube via the Data API.

        NOTE: Requires OAuth2 credentials. On first run, the user must complete
        the Google OAuth consent flow (one-time). After that it's fully automated.
        Video file must be generated by a video generation service (RunwayML, Kling, etc.)
        """
        if self.settings.dry_run or not self.settings.youtube_refresh_token:
            logger.info("[DRY RUN] Would upload to YouTube: %s", script_data.get("title"))
            return {
                "success": True,
                "platform_id": f"mock_yt_{datetime.utcnow().timestamp():.0f}",
                "dry_run": True,
                "title": script_data.get("title"),
            }

        try:
            from google.oauth2.credentials import Credentials
            from googleapiclient.discovery import build
            from googleapiclient.http import MediaFileUpload

            creds = Credentials(
                token=None,
                refresh_token=self.settings.youtube_refresh_token,
                client_id=self.settings.youtube_client_id,
                client_secret=self.settings.youtube_client_secret,
                token_uri="https://oauth2.googleapis.com/token",
            )

            youtube = build("youtube", "v3", credentials=creds)
            request_body = {
                "snippet": {
                    "title": script_data.get("title", "")[:100],
                    "description": script_data.get("description", "")[:5000],
                    "tags": script_data.get("tags", [])[:500],
                    "categoryId": "22",  # People & Blogs
                },
                "status": {
                    "privacyStatus": "public",
                    "selfDeclaredMadeForKids": False,
                },
            }

            if video_path:
                media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
                insert_request = youtube.videos().insert(
                    part="snippet,status",
                    body=request_body,
                    media_body=media,
                )
                response = insert_request.execute()
                video_id = response.get("id", "")
            else:
                # No video file yet — create a draft metadata entry
                video_id = f"draft_{datetime.utcnow().timestamp():.0f}"

            logger.info("YouTube upload success: %s (ID: %s)", script_data.get("title"), video_id)
            return {"success": True, "platform_id": video_id, "title": script_data.get("title")}

        except Exception as e:
            logger.error("YouTube upload failed: %s", e)
            return {"success": False, "error": str(e)}

    async def set_thumbnail(self, video_id: str, thumbnail_path: str) -> bool:
        """Set a custom thumbnail for a video."""
        if self.settings.dry_run:
            return True
        logger.info("Set thumbnail for video %s", video_id)
        return True

    def generate_upload_schedule(self, scripts: list[dict], shorts_per_day: int = 2, longform_per_week: int = 3) -> list[dict]:
        """Create an optimized upload schedule."""
        schedule = []
        now = datetime.utcnow()
        shorts = [s for s in scripts if s.get("subtype") == "shorts"]
        longform = [s for s in scripts if s.get("subtype") == "longform"]

        for i, script in enumerate(shorts):
            schedule.append({
                "script": script,
                "type": "shorts",
                "scheduled_at": (now.replace(hour=18) if i == 0 else now).isoformat(),
                "status": "scheduled",
            })

        for i, script in enumerate(longform):
            from datetime import timedelta
            days = (i * 7) // longform_per_week
            schedule.append({
                "script": script,
                "type": "longform",
                "scheduled_at": (now + timedelta(days=days)).replace(hour=15).isoformat(),
                "status": "scheduled",
            })

        return schedule
